export const MY_LIFE_NOW = `
<p>
  I currently live with my wife, dog and cat just outside Denver, CO. The view is gorgeous!
</p>
<p>
  I spend most of my time writing code, sometimes 10 or 12 hours a day. I absolutely love coding, and even "work" usually feels like "fun time".
</p>
<p>
  When I am not coding, I am usually playing video games. My current favorites are <em>Geshin Impact</em>, <em>The Sims 4 (heavily modded)</em> and <em>Kingdom of Loathing</em>.
</p>
<p>
  Most autumns, my wife and I start our yearly reading rush, where we read through series after series for several months. This year we will likely finish the <em>Wrinkle in Time</em> series by Madeleine L'Engle and the <em>Shadow and Bone</em> series by Leigh Bardugo at a minimum.
</p>
<p>
  My wife and I are both enthusiastic about the ketogenic lifestyle, and are always on the lookout for new, delicious recipes.
</p>
`

export const PERSONAL_INTERESTS = `
<ul>
  <li>
    <ul>
      <li>
        <p>
          Faith
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Family
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Coding
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Video Games
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Storytelling
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Reading
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Anime (Watching)
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Hiking / Caving
        </p>
      </li>
    </ul>
  </li>
</ul>
`

export const HOW_I_GOT_STARTED = `
<p>
  While I was in the military, my wife and I played a game called Second Life&trade;. I enjoyed the gameplay somewhat, but what I most enjoyed was working with the built-in scripting language, LSL. I often had free time away from computer access, so I would fill up that time hand-writing LSL code to create various in-game items for my wife and I to interact with. (My favorite was a pillow that your avatar could beat up, sending feathers flying.)
</p>
<p>
  I didn't think much about it at the time, but after I left the military, I found the journals I had used for LSL. I had filled up eight journals, front-and-back with HAND-WRITTEN code! I realized that I loved coding far more than I had ever known.
</p>
<p>
  So, I taught myself Python and was hooked forever. Soon after, I saw an opportunity at Flatiron School, where I learned Ruby on Rails, React and Redux, and my appetite for learning new code has been whetted.
</p>
<p>
  Since graduating in December 2020, I have taught myself many more languages. I can't get enough; this is a process that will continue throughout the rest of my life.
</p>
`

export const NEXT_THINGS_TO_LEARN = `
<ul>
  <li>
    <ul>
      <li>
        <p>
          GraphQL
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Apollo
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Kubernetes
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          TensorFlow
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Brainf**k
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          MongoDB
        </p>
      </li>
    </ul>
  </li>
</ul>
`

export const SKILLS = `
<ul>
  <li>
    <ul>
      <li>
        <p>
          Frontend:
        </p>
      </li>
      <li>
        <p>
          TypeScript
        </p>
      </li>
      <li>
        <p>
          JavaScript
        </p>
      </li>
      <li>
        <p>
          Next.js
        </p>
      </li>
      <li>
        <p>
          React
        </p>
      </li>
      <li>
        <p>
          Redux
        </p>
      </li>
      <li>
        <p>
          HTML5
        </p>
      </li>
      <li>
        <p>
          CSS3
        </p>
      </li>
      <li>
        <p>
          Sass/SCSS
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Backend:
        </p>
      </li>
      <li>
        <p>
          Ruby on Rails
        </p>
      </li>
      <li>
        <p>
          Ruby
        </p>
      </li>
      <li>
        <p>
          Python
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Databases:
        </p>
      </li>
      <li>
        <p>
          SQL
        </p>
      </li>
      <li>
        <p>
          PostgreSQL
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Other APIs & Frameworks:
        </p>
      </li>
      <li>
        <p>
          Flask
        </p>
      </li>
      <li>
        <p>
          Django
        </p>
      </li>
      <li>
        <p>
          SQLAlchemy
        </p>
      </li>
      <li>
        <p>
          GreenSock Animation Platform (GSAP)
        </p>
      </li>
      <li>
        <p>
          Bootstrap
        </p>
      </li>
    </ul>
  </li>
</ul>
`
