export const MY_LIFE_NOW = `
Officiis noluisse assentior export constituto iure turpis faucibus fusce morbi eu meliore dolor qui. Aut quo mi interdum aliquet labores corrumpit on ex vidisse putent quando possim. Pertinax urbanitas honestatis viverra maecenas quaestio ornare lobortis vero ei laboramus! Posidonium tale aliquam. Adhuc vivamus massa noster habeo dolor sem pro cetero cum ridens movet nemore el sint. Iure sonet platonem forensibus ea in ei veniam dicta omittam no patrioque mel pri? Ornare purus qui ultrices altera doming albucius meliore pretium aeque cursus nullam homero. Quodsi eleifend usu rationibus apeirian persecuti putant no minimum patrioque. Natum velit forensibus ante prima.
`

export const PERSONAL_INTERESTS = `
Fames aliquip volumus. Explicari dicant cursus ac dicat curabitur ante. Veniam posuere pri nisl. On mollis cetero possim vitae scripta agam minimum eum sonet tota. Dicant posuere assentior ornatus gravida lucilius. Elit omnium numquam porta quis pro eius accumsan consectetur enim corrumpit. Pericula sint iriure. Fabulas arcu brute nam primis minim mel harum in repudiandae detracto quaestio dolore! Eget ancillae illum falli iisque magna omittantur suscipit patrioque varius varius minim ac adversarium bonorum.
`

export const HOW_I_GOT_STARTED = `
<p>
  While I was in the military, my wife and I played a game called Second Life&trade;. I enjoyed the gameplay somewhat, but what I most enjoyed was working with the built-in scripting language, LSL. I often had free time away from computer access, so I would fill up that time hand-writing LSL code to create various in-game items for my wife and I to interact with. (My favorite was a pillow that your avatar could beat up, sending feathers flying.)
</p>
<p>
  I didn't think much about it at the time, but after I left the military, I found the journals I had used for LSL. I had filled up eight journals, front-and-back with HAND-WRITTEN code! I realized that I loved coding far more than I had ever known.
</p>
<p>
  So, I taught myself Python and was hooked forever. Soon after, I saw an opportunity at Flatiron School, where I learned Ruby on Rails, React and Redux, and my appetite for learning new code has been whetted.
</p>
<p>
  Since graduating in December 2020, I have taught myself many more languages. I can't get enough; this is a process that will cotinue throughout the rest of my life.
</p>
`

export const NEXT_THINGS_TO_LEARN = `
<ul>
  <li>
    <ul>
      <li>
        <p>
          GraphQL
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Apollo
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Kubernetes
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          TensorFlow
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Brainf**k
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          MongoDB
        </p>
      </li>
    </ul>
  </li>
</ul>
`

export const SKILLS = `
<ul>
  <li>
    <ul>
      <li>
        <p>
          Frontend:
        </p>
      </li>
      <li>
        <p>
          TypeScript
        </p>
      </li>
      <li>
        <p>
          JavaScript
        </p>
      </li>
      <li>
        <p>
          Next.js
        </p>
      </li>
      <li>
        <p>
          React
        </p>
      </li>
      <li>
        <p>
          Redux
        </p>
      </li>
      <li>
        <p>
          HTML5
        </p>
      </li>
      <li>
        <p>
          CSS3
        </p>
      </li>
      <li>
        <p>
          Sass/SCSS
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Backend:
        </p>
      </li>
      <li>
        <p>
          Ruby on Rails
        </p>
      </li>
      <li>
        <p>
          Ruby
        </p>
      </li>
      <li>
        <p>
          Python
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Databases:
        </p>
      </li>
      <li>
        <p>
          SQL
        </p>
      </li>
      <li>
        <p>
          PostgreSQL
        </p>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <p>
          Other APIs & Frameworks:
        </p>
      </li>
      <li>
        <p>
          Flask
        </p>
      </li>
      <li>
        <p>
          Django
        </p>
      </li>
      <li>
        <p>
          SQLAlchemy
        </p>
      </li>
      <li>
        <p>
          GreenSock Animation Platform (GSAP)
        </p>
      </li>
      <li>
        <p>
          Bootstrap
        </p>
      </li>
    </ul>
  </li>
</ul>
`
